dist: xenial
services:
  - xvfb
sudo: required

language: python
python:
    - 3.6
    - 3.7
    - 3.8

env:
    TEST_ENV: travis

install:
    - sudo apt-get install libmpv1 -y --force-yes
    # https://github.com/pytest-dev/pytest-qt/issues/266
    - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
    # travis will auto create a virtualenv, as a result,
    # we can't import from system site-package
    # - sudo apt-get install python3-dbus python3-dbus.mainloop.pyqt5 -y
    #
    # TODO: think about a way to test mpris2 in travis environment
    - pip install pyqt5==5.14.0 pyopengl
    - pip install coveralls
    - pip install sphinx_rtd_theme
    - pip install -e .[dev]

script:
    - make test
    - make integration_test

after_success:
  - coveralls
