name: Release for windows
on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch:

jobs:
  build-n-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
        pip install pyinstaller
        pip install pyinstaller-versionfile
        pip install -e .[win32,battery,cookies]
    - name: Download mpv-1.dll
      run: |
        choco install curl
        curl -L https://github.com/feeluown/FeelUOwn/releases/download/v3.8/mpv-1.dll -o mpv-1.dll
    - name: Bundle
      run: |
        # Add current working directory to path so that mpv-1.dll can be found.
        $env:path += ";."
        make bundle
    - name: Archive
      run: |
        # List dist to help double check if bundle is ok.
        ls dist/
        powershell Compress-Archive dist/FeelUOwn dist/FeelUOwn-windows.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FeelUOwn-windows.zip
        path: dist/FeelUOwn-windows.zip
    - name: Upload to release page
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/FeelUOwn-windows.zip
